// Generated by scripts/generate-db-types.mjs — do not edit by hand.
// Regenerate: npm run gen:types
// Source: live Supabase PostgREST schema (2026-07-08T20:25:33.929Z)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      business_settings: {
        Row: {
          id: boolean
          business_name: string
          currency: string
          default_delivery_fee: number
          tax_rate: number
          instagram_handle?: string | null
          updated_at: string
        }
        Insert: {
          id?: boolean
          business_name?: string
          currency?: string
          default_delivery_fee?: number
          tax_rate?: number
          instagram_handle?: string | null
          updated_at?: string
        }
        Update: {
          id?: boolean
          business_name?: string | null
          currency?: string | null
          default_delivery_fee?: number
          tax_rate?: number
          instagram_handle?: string | null
          updated_at?: string | null
        }
        Relationships: [

        ]
      }
      cash_flow_entries: {
        Row: {
          id: string
          entry_type: Database["public"]["Enums"]["cash_flow_type"]
          category: string
          amount: number
          description?: string | null
          entry_date: string
          related_order_id?: string
          related_expense_id?: string
          related_purchase_id?: string
          created_by?: string
          created_at: string
          account_id?: string
        }
        Insert: {
          id?: string
          entry_type?: Database["public"]["Enums"]["cash_flow_type"]
          category?: string
          amount?: number
          description?: string | null
          entry_date?: string
          related_order_id?: string
          related_expense_id?: string
          related_purchase_id?: string
          created_by?: string
          created_at?: string
          account_id?: string
        }
        Update: {
          id?: string
          entry_type?: Database["public"]["Enums"]["cash_flow_type"]
          category?: string | null
          amount?: number
          description?: string | null
          entry_date?: string | null
          related_order_id?: string
          related_expense_id?: string
          related_purchase_id?: string
          created_by?: string
          created_at?: string | null
          account_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "related_order_id_fkey"
            columns: ["related_order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "related_expense_id_fkey"
            columns: ["related_expense_id"]
            isOneToOne: false
            referencedRelation: "expenses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "related_purchase_id_fkey"
            columns: ["related_purchase_id"]
            isOneToOne: false
            referencedRelation: "purchases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "financial_accounts"
            referencedColumns: ["id"]
          }
        ]
      }
      categories: {
        Row: {
          id: string
          name: string
          description?: string | null
          display_order: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name?: string
          description?: string | null
          display_order?: number
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          description?: string | null
          display_order?: number
          is_active?: boolean
          created_at?: string | null
        }
        Relationships: [

        ]
      }
      customer_addresses: {
        Row: {
          id: string
          customer_id: string
          label: string
          address_line: string
          city?: string | null
          state?: string | null
          reference?: string | null
          latitude?: number
          longitude?: number
          is_default: boolean
          created_at: string
        }
        Insert: {
          id?: string
          customer_id?: string
          label?: string
          address_line?: string
          city?: string | null
          state?: string | null
          reference?: string | null
          latitude?: number
          longitude?: number
          is_default?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          customer_id?: string
          label?: string | null
          address_line?: string | null
          city?: string | null
          state?: string | null
          reference?: string | null
          latitude?: number
          longitude?: number
          is_default?: boolean
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          }
        ]
      }
      customers: {
        Row: {
          id: string
          user_id?: string
          full_name: string
          email?: string | null
          phone: string
          instagram_handle?: string | null
          notes?: string | null
          is_active: boolean
          created_at: string
          updated_at: string
          cedula?: string | null
        }
        Insert: {
          id?: string
          user_id?: string
          full_name?: string
          email?: string | null
          phone?: string
          instagram_handle?: string | null
          notes?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
          cedula?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          full_name?: string | null
          email?: string | null
          phone?: string | null
          instagram_handle?: string | null
          notes?: string | null
          is_active?: boolean
          created_at?: string | null
          updated_at?: string | null
          cedula?: string | null
        }
        Relationships: [

        ]
      }
      exchange_rates: {
        Row: {
          id: string
          currency: Database["public"]["Enums"]["currency_code"]
          rate: number
          updated_by?: string
          updated_at: string
        }
        Insert: {
          id?: string
          currency?: Database["public"]["Enums"]["currency_code"]
          rate?: number
          updated_by?: string
          updated_at?: string
        }
        Update: {
          id?: string
          currency?: Database["public"]["Enums"]["currency_code"]
          rate?: number
          updated_by?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      expenses: {
        Row: {
          id: string
          category: Database["public"]["Enums"]["expense_category"]
          description: string
          amount: number
          expense_date: string
          is_recurring: boolean
          created_by?: string
          created_at: string
          account_id?: string
        }
        Insert: {
          id?: string
          category?: Database["public"]["Enums"]["expense_category"]
          description?: string
          amount?: number
          expense_date?: string
          is_recurring?: boolean
          created_by?: string
          created_at?: string
          account_id?: string
        }
        Update: {
          id?: string
          category?: Database["public"]["Enums"]["expense_category"]
          description?: string | null
          amount?: number
          expense_date?: string | null
          is_recurring?: boolean
          created_by?: string
          created_at?: string | null
          account_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "financial_accounts"
            referencedColumns: ["id"]
          }
        ]
      }
      financial_accounts: {
        Row: {
          id: string
          name: string
          account_type: Database["public"]["Enums"]["account_type"]
          currency: Database["public"]["Enums"]["currency_code"]
          account_number?: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name?: string
          account_type?: Database["public"]["Enums"]["account_type"]
          currency?: Database["public"]["Enums"]["currency_code"]
          account_number?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          account_type?: Database["public"]["Enums"]["account_type"]
          currency?: Database["public"]["Enums"]["currency_code"]
          account_number?: string | null
          is_active?: boolean
          created_at?: string | null
        }
        Relationships: [

        ]
      }
      ingredients: {
        Row: {
          id: string
          name: string
          unit_id: string
          default_supplier_id?: string
          cost_per_unit: number
          current_stock: number
          min_stock: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name?: string
          unit_id?: string
          default_supplier_id?: string
          cost_per_unit?: number
          current_stock?: number
          min_stock?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          unit_id?: string
          default_supplier_id?: string
          cost_per_unit?: number
          current_stock?: number
          min_stock?: number
          is_active?: boolean
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "unit_id_fkey"
            columns: ["unit_id"]
            isOneToOne: false
            referencedRelation: "units"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "default_supplier_id_fkey"
            columns: ["default_supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          }
        ]
      }
      inventory_movements: {
        Row: {
          id: string
          ingredient_id: string
          movement_type: Database["public"]["Enums"]["movement_type"]
          quantity: number
          resulting_stock: number
          reference_type?: string | null
          reference_id?: string
          notes?: string | null
          created_by?: string
          created_at: string
        }
        Insert: {
          id?: string
          ingredient_id?: string
          movement_type?: Database["public"]["Enums"]["movement_type"]
          quantity?: number
          resulting_stock?: number
          reference_type?: string | null
          reference_id?: string
          notes?: string | null
          created_by?: string
          created_at?: string
        }
        Update: {
          id?: string
          ingredient_id?: string
          movement_type?: Database["public"]["Enums"]["movement_type"]
          quantity?: number
          resulting_stock?: number
          reference_type?: string | null
          reference_id?: string
          notes?: string | null
          created_by?: string
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      notifications_log: {
        Row: {
          id: string
          customer_id?: string
          order_id?: string
          channel: Database["public"]["Enums"]["notification_channel"]
          notification_type: Database["public"]["Enums"]["notification_type"]
          recipient: string
          subject?: string | null
          status: Database["public"]["Enums"]["notification_status"]
          error_message?: string | null
          sent_at?: string | null
          created_at: string
        }
        Insert: {
          id?: string
          customer_id?: string
          order_id?: string
          channel?: Database["public"]["Enums"]["notification_channel"]
          notification_type?: Database["public"]["Enums"]["notification_type"]
          recipient?: string
          subject?: string | null
          status?: Database["public"]["Enums"]["notification_status"]
          error_message?: string | null
          sent_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          customer_id?: string
          order_id?: string
          channel?: Database["public"]["Enums"]["notification_channel"]
          notification_type?: Database["public"]["Enums"]["notification_type"]
          recipient?: string | null
          subject?: string | null
          status?: Database["public"]["Enums"]["notification_status"]
          error_message?: string | null
          sent_at?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          }
        ]
      }
      option_groups: {
        Row: {
          id: string
          name: string
          selection_type: Database["public"]["Enums"]["selection_type"]
          is_required: boolean
          min_select: number
          max_select?: number
          display_order: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name?: string
          selection_type?: Database["public"]["Enums"]["selection_type"]
          is_required?: boolean
          min_select?: number
          max_select?: number
          display_order?: number
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          selection_type?: Database["public"]["Enums"]["selection_type"]
          is_required?: boolean
          min_select?: number
          max_select?: number
          display_order?: number
          is_active?: boolean
          created_at?: string | null
        }
        Relationships: [

        ]
      }
      option_items: {
        Row: {
          id: string
          option_group_id: string
          name: string
          price_modifier: number
          ingredient_id?: string
          ingredient_quantity?: number
          display_order: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          option_group_id?: string
          name?: string
          price_modifier?: number
          ingredient_id?: string
          ingredient_quantity?: number
          display_order?: number
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          option_group_id?: string
          name?: string | null
          price_modifier?: number
          ingredient_id?: string
          ingredient_quantity?: number
          display_order?: number
          is_active?: boolean
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "option_group_id_fkey"
            columns: ["option_group_id"]
            isOneToOne: false
            referencedRelation: "option_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          }
        ]
      }
      order_item_options: {
        Row: {
          id: string
          order_item_id: string
          option_item_id?: string
          name: string
          price_modifier: number
          created_at: string
        }
        Insert: {
          id?: string
          order_item_id?: string
          option_item_id?: string
          name?: string
          price_modifier?: number
          created_at?: string
        }
        Update: {
          id?: string
          order_item_id?: string
          option_item_id?: string
          name?: string | null
          price_modifier?: number
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_item_id_fkey"
            columns: ["order_item_id"]
            isOneToOne: false
            referencedRelation: "order_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "option_item_id_fkey"
            columns: ["option_item_id"]
            isOneToOne: false
            referencedRelation: "option_items"
            referencedColumns: ["id"]
          }
        ]
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string
          quantity: number
          unit_price: number
          subtotal?: number
          notes?: string | null
          kitchen_status: Database["public"]["Enums"]["kitchen_item_status"]
          created_at: string
        }
        Insert: {
          id?: string
          order_id?: string
          product_id?: string
          quantity?: number
          unit_price?: number
          subtotal?: number
          notes?: string | null
          kitchen_status?: Database["public"]["Enums"]["kitchen_item_status"]
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          product_id?: string
          quantity?: number
          unit_price?: number
          subtotal?: number
          notes?: string | null
          kitchen_status?: Database["public"]["Enums"]["kitchen_item_status"]
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          }
        ]
      }
      order_status_history: {
        Row: {
          id: string
          order_id: string
          status: Database["public"]["Enums"]["order_status"]
          changed_by?: string
          notes?: string | null
          created_at: string
        }
        Insert: {
          id?: string
          order_id?: string
          status?: Database["public"]["Enums"]["order_status"]
          changed_by?: string
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          status?: Database["public"]["Enums"]["order_status"]
          changed_by?: string
          notes?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      orders: {
        Row: {
          id: string
          order_number: string
          customer_id: string
          status: Database["public"]["Enums"]["order_status"]
          order_type: Database["public"]["Enums"]["order_type"]
          delivery_address_id?: string
          subtotal: number
          discount: number
          delivery_fee: number
          total: number
          payment_method?: Database["public"]["Enums"]["payment_method"]
          payment_status: Database["public"]["Enums"]["payment_status"]
          notes?: string | null
          estimated_ready_at?: string | null
          placed_at: string
          confirmed_at?: string | null
          ready_at?: string | null
          delivered_at?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          created_by?: string
          created_at: string
          updated_at: string
          currency: Database["public"]["Enums"]["currency_code"]
          exchange_rate: number
          total_currency: number
        }
        Insert: {
          id?: string
          order_number?: string
          customer_id?: string
          status?: Database["public"]["Enums"]["order_status"]
          order_type?: Database["public"]["Enums"]["order_type"]
          delivery_address_id?: string
          subtotal?: number
          discount?: number
          delivery_fee?: number
          total?: number
          payment_method?: Database["public"]["Enums"]["payment_method"]
          payment_status?: Database["public"]["Enums"]["payment_status"]
          notes?: string | null
          estimated_ready_at?: string | null
          placed_at?: string
          confirmed_at?: string | null
          ready_at?: string | null
          delivered_at?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
          currency?: Database["public"]["Enums"]["currency_code"]
          exchange_rate?: number
          total_currency?: number
        }
        Update: {
          id?: string
          order_number?: string | null
          customer_id?: string
          status?: Database["public"]["Enums"]["order_status"]
          order_type?: Database["public"]["Enums"]["order_type"]
          delivery_address_id?: string
          subtotal?: number
          discount?: number
          delivery_fee?: number
          total?: number
          payment_method?: Database["public"]["Enums"]["payment_method"]
          payment_status?: Database["public"]["Enums"]["payment_status"]
          notes?: string | null
          estimated_ready_at?: string | null
          placed_at?: string | null
          confirmed_at?: string | null
          ready_at?: string | null
          delivered_at?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          created_by?: string
          created_at?: string | null
          updated_at?: string | null
          currency?: Database["public"]["Enums"]["currency_code"]
          exchange_rate?: number
          total_currency?: number
        }
        Relationships: [
          {
            foreignKeyName: "customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_address_id_fkey"
            columns: ["delivery_address_id"]
            isOneToOne: false
            referencedRelation: "customer_addresses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      payments: {
        Row: {
          id: string
          order_id: string
          amount: number
          method: Database["public"]["Enums"]["payment_method"]
          status: Database["public"]["Enums"]["payment_status"]
          reference?: string | null
          paid_at: string
          created_by?: string
          created_at: string
          currency: Database["public"]["Enums"]["currency_code"]
          exchange_rate: number
          amount_currency: number
          account_id?: string
        }
        Insert: {
          id?: string
          order_id?: string
          amount?: number
          method?: Database["public"]["Enums"]["payment_method"]
          status?: Database["public"]["Enums"]["payment_status"]
          reference?: string | null
          paid_at?: string
          created_by?: string
          created_at?: string
          currency?: Database["public"]["Enums"]["currency_code"]
          exchange_rate?: number
          amount_currency?: number
          account_id?: string
        }
        Update: {
          id?: string
          order_id?: string
          amount?: number
          method?: Database["public"]["Enums"]["payment_method"]
          status?: Database["public"]["Enums"]["payment_status"]
          reference?: string | null
          paid_at?: string | null
          created_by?: string
          created_at?: string | null
          currency?: Database["public"]["Enums"]["currency_code"]
          exchange_rate?: number
          amount_currency?: number
          account_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "financial_accounts"
            referencedColumns: ["id"]
          }
        ]
      }
      price_history: {
        Row: {
          id: string
          product_id?: string
          old_price?: number
          new_price: number
          changed_by?: string
          created_at: string
        }
        Insert: {
          id?: string
          product_id?: string
          old_price?: number
          new_price?: number
          changed_by?: string
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          old_price?: number
          new_price?: number
          changed_by?: string
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      product_option_groups: {
        Row: {
          id: string
          product_id: string
          option_group_id: string
          display_order: number
        }
        Insert: {
          id?: string
          product_id?: string
          option_group_id?: string
          display_order?: number
        }
        Update: {
          id?: string
          product_id?: string
          option_group_id?: string
          display_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "option_group_id_fkey"
            columns: ["option_group_id"]
            isOneToOne: false
            referencedRelation: "option_groups"
            referencedColumns: ["id"]
          }
        ]
      }
      products: {
        Row: {
          id: string
          sku?: string | null
          name: string
          description?: string | null
          category_id?: string
          base_price: number
          image_url?: string | null
          track_inventory: boolean
          is_active: boolean
          display_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          sku?: string | null
          name?: string
          description?: string | null
          category_id?: string
          base_price?: number
          image_url?: string | null
          track_inventory?: boolean
          is_active?: boolean
          display_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          sku?: string | null
          name?: string | null
          description?: string | null
          category_id?: string
          base_price?: number
          image_url?: string | null
          track_inventory?: boolean
          is_active?: boolean
          display_order?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          }
        ]
      }
      profiles: {
        Row: {
          id: string
          role: Database["public"]["Enums"]["user_role"]
          full_name: string
          phone?: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
          full_name?: string
          phone?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
          full_name?: string | null
          phone?: string | null
          is_active?: boolean
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [

        ]
      }
      purchase_items: {
        Row: {
          id: string
          purchase_id: string
          ingredient_id: string
          quantity: number
          unit_cost: number
          subtotal?: number
        }
        Insert: {
          id?: string
          purchase_id?: string
          ingredient_id?: string
          quantity?: number
          unit_cost?: number
          subtotal?: number
        }
        Update: {
          id?: string
          purchase_id?: string
          ingredient_id?: string
          quantity?: number
          unit_cost?: number
          subtotal?: number
        }
        Relationships: [
          {
            foreignKeyName: "purchase_id_fkey"
            columns: ["purchase_id"]
            isOneToOne: false
            referencedRelation: "purchases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          }
        ]
      }
      purchase_payments: {
        Row: {
          id: string
          purchase_id: string
          amount: number
          currency: Database["public"]["Enums"]["currency_code"]
          exchange_rate: number
          amount_currency: number
          method: Database["public"]["Enums"]["payment_method"]
          account_id?: string
          reference?: string | null
          paid_at: string
          created_by?: string
          created_at: string
        }
        Insert: {
          id?: string
          purchase_id?: string
          amount?: number
          currency?: Database["public"]["Enums"]["currency_code"]
          exchange_rate?: number
          amount_currency?: number
          method?: Database["public"]["Enums"]["payment_method"]
          account_id?: string
          reference?: string | null
          paid_at?: string
          created_by?: string
          created_at?: string
        }
        Update: {
          id?: string
          purchase_id?: string
          amount?: number
          currency?: Database["public"]["Enums"]["currency_code"]
          exchange_rate?: number
          amount_currency?: number
          method?: Database["public"]["Enums"]["payment_method"]
          account_id?: string
          reference?: string | null
          paid_at?: string | null
          created_by?: string
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "purchase_id_fkey"
            columns: ["purchase_id"]
            isOneToOne: false
            referencedRelation: "purchases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "financial_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      purchases: {
        Row: {
          id: string
          purchase_number: string
          supplier_id: string
          status: Database["public"]["Enums"]["purchase_status"]
          invoice_number?: string | null
          purchase_date: string
          received_date?: string | null
          total: number
          notes?: string | null
          created_by?: string
          created_at: string
          updated_at: string
          payment_status: Database["public"]["Enums"]["payment_status"]
        }
        Insert: {
          id?: string
          purchase_number?: string
          supplier_id?: string
          status?: Database["public"]["Enums"]["purchase_status"]
          invoice_number?: string | null
          purchase_date?: string
          received_date?: string | null
          total?: number
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
          payment_status?: Database["public"]["Enums"]["payment_status"]
        }
        Update: {
          id?: string
          purchase_number?: string | null
          supplier_id?: string
          status?: Database["public"]["Enums"]["purchase_status"]
          invoice_number?: string | null
          purchase_date?: string | null
          received_date?: string | null
          total?: number
          notes?: string | null
          created_by?: string
          created_at?: string | null
          updated_at?: string | null
          payment_status?: Database["public"]["Enums"]["payment_status"]
        }
        Relationships: [
          {
            foreignKeyName: "supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      recipe_ingredients: {
        Row: {
          id: string
          recipe_id: string
          ingredient_id: string
          quantity: number
          unit_id: string
          created_at: string
        }
        Insert: {
          id?: string
          recipe_id?: string
          ingredient_id?: string
          quantity?: number
          unit_id?: string
          created_at?: string
        }
        Update: {
          id?: string
          recipe_id?: string
          ingredient_id?: string
          quantity?: number
          unit_id?: string
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "unit_id_fkey"
            columns: ["unit_id"]
            isOneToOne: false
            referencedRelation: "units"
            referencedColumns: ["id"]
          }
        ]
      }
      recipes: {
        Row: {
          id: string
          product_id: string
          name: string
          yield_quantity: number
          instructions?: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          product_id?: string
          name?: string
          yield_quantity?: number
          instructions?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          name?: string | null
          yield_quantity?: number
          instructions?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          }
        ]
      }
      suppliers: {
        Row: {
          id: string
          name: string
          contact_name?: string | null
          phone?: string | null
          email?: string | null
          address?: string | null
          notes?: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name?: string
          contact_name?: string | null
          phone?: string | null
          email?: string | null
          address?: string | null
          notes?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          contact_name?: string | null
          phone?: string | null
          email?: string | null
          address?: string | null
          notes?: string | null
          is_active?: boolean
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [

        ]
      }
      units: {
        Row: {
          id: string
          name: string
          abbreviation: string
          unit_type: Database["public"]["Enums"]["unit_type"]
          created_at: string
        }
        Insert: {
          id?: string
          name?: string
          abbreviation?: string
          unit_type?: Database["public"]["Enums"]["unit_type"]
          created_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          abbreviation?: string | null
          unit_type?: Database["public"]["Enums"]["unit_type"]
          created_at?: string | null
        }
        Relationships: [

        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      account_type: "cash" | "bank" | "digital_wallet" | "other"
      cash_flow_type: "income" | "expense"
      currency_code: "USD" | "EUR" | "VES"
      expense_category: "rent" | "utilities" | "salaries" | "marketing" | "maintenance" | "supplies" | "delivery" | "other"
      kitchen_item_status: "pending" | "preparing" | "ready"
      movement_type: "purchase_in" | "sale_out" | "adjustment_in" | "adjustment_out" | "waste" | "production_in" | "production_out"
      notification_channel: "email"
      notification_status: "pending" | "sent" | "failed"
      notification_type: "order_confirmed" | "order_in_kitchen" | "order_ready" | "order_out_for_delivery" | "order_delivered" | "order_cancelled" | "welcome"
      order_status: "pending" | "confirmed" | "in_kitchen" | "ready" | "out_for_delivery" | "delivered" | "cancelled"
      order_type: "delivery" | "pickup"
      payment_method: "cash" | "card" | "transfer" | "other" | "pago_movil" | "zelle"
      payment_status: "pending" | "paid" | "partial" | "refunded" | "failed"
      purchase_status: "pending" | "received" | "cancelled"
      selection_type: "single" | "multiple"
      unit_type: "weight" | "volume" | "count"
      user_role: "admin" | "manager" | "kitchen" | "delivery" | "customer"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema["Tables"] & PublicSchema["Views"])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema["Tables"] & PublicSchema["Views"])
    ? (PublicSchema["Tables"] & PublicSchema["Views"])[PublicTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
    ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
    ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof PublicSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema["Enums"]
    ? PublicSchema["Enums"][PublicEnumNameOrOptions]
    : never
